sunradius=float(input("Enter the radius of the Sun (miles) -> ", ))
print(int(sunradius))
moonradius=float(input("Enter the radius of the Moon (miles) -> ", ))
print(int(moonradius))
maxdistancesun=float(input("Enter the maximum distance to the Sun (miles) -> ", ))
print(int(maxdistancesun))
mindistance=float(input("Enter the minimum distance to the Moon (miles) -> ", ))
print(int(mindistance))
moonrate=float(input("Enter the rate the Moon is moving away (in/year) -> ", ))
print(format(moonrate, '.1f'))
equaldistance=(maxdistancesun*(moonradius/sunradius))
print("The Moon will have exactly the same apparent size as the Sun when it is", format(equaldistance, '.2f'), "miles away.")
morerecede=equaldistance-mindistance
timeleft=int(((morerecede*5280*12)/moonrate))
print("The Moon will need to recede another", format(morerecede, '.2f'), "miles")
print("Which will occur in", timeleft, "years at the current rate.")